name: Slack Bot
on:
  workflow_dispatch:
    inputs:
      date:
        required: true
        description: 日付 (例えば2022年1月1日の場合は 20220101 のように入力してください)
        default: ""
      prefecture:
        required: true
        description: 都道府県 (例\:東京都、神奈川県)
        default: ""
      channel:
        required: true
        description: チャンネルIDまたはチャンネル名
        default: ""

jobs:
  report-covid19:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.patients }}
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: install rust tool chain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: execute
        id: execute-cargo-run
        run: echo "::set-output name=RESULT::$(cargo run ${{ github.event.inputs.date }} ${{ github.event.inputs.prefecture }} 2>/dev/null)"
      # - name: Post to a Slack channel
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.17.0
      #   with:
      #     # Slack channel id, channel name, or user id to post message.
      #     # See also: https://api.slack.com/methods/chat.postMessage#channels
      #     channel-id: ${{ github.event.inputs.channel }}
      #     # For posting a simple plain text message
      #     slack-message: "東京都の20220122の感染者数は ${{ steps.execute-cargo-run.outputs.RESULT }}人でした！ "
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Send custom JSON data to Slack workflow
        id: slack_payload
        uses: slackapi/slack-github-action@v1.17.0
        with:
          channel-id: ${{ github.event.inputs.channel }}
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "plain_text",
                    "text": "${{ steps.execute-cargo-run.outputs.prefecture }}の${{ steps.execute-cargo-run.outputs.date }}の感染者数は ${{ steps.execute-cargo-run.outputs.RESULT }}人でした！ ",
                    "emoji": true
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
